"""Create Message model

Revision ID: 33109b1c3be2
Revises: 
Create Date: 2024-04-08 16:34:06.466824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33109b1c3be2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
